### ISSUE TITLE
Chromium Edge browser

### ISSUE THREAD

**Issue by denimnani** [sommoMicc/EdgeTana#1]
This extension is no longer working with the new edge browser.
 I'm really hoping for a new update.
Thank you for the great work

**Comment by sommoMicc** [comment]
Hi, the new Edge browser (which I'm currently using) is based on Chromium
and, with the last couple of updates, the possibility to install Chrome
plugin from the Chrome Web Storie was added.

For Google Chrome (so for Edge Chromium) there is already a plugin called
ChromeTana (which inspired me to build EdgeTana). I suggest you to check
ChromeTana and, if it does not meet your needs, please reply to this thread
and I will try to port EdgeTana on Chromium.

Regards

**Comment by denimnani** [comment]
Yep after I open the issue i found out that the extension for google chrome work well in the new Edge.
Thanks for your support
